app1/urls.py
from django.urls import path
from app1.views import *
app_name='first'
urlpatterns=[
    path('first/',first,name='first'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='second'
urlpatterns=[
    path('second/',second,name='second'),
]

project22/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def second(request):
    return render(request,'second.html')

templates/first.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
       <h1>This is my first views property</h1>
       <img src="{% static 'images/virat.jpg'  %}" width="300px" height="200px" alt="" srcset=""><br>
       <a href="{% url 'second:second' %}">Click Here</a>
    </center>
</body>
</html>

templates/second.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/c2.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is my second views property</h1>
        <img src="{% static 'images/Bhumrah.jfif'  %}" width="300px" height="200px" alt="" srcset=""><br>
        <a href="{% url 'first:first' %}">Click Here</a>
     </center>
</body>
</html>